# 增加全部可增加数值(对宝石无效)
武器等级:
 - "§7★"
 - "§a★★"
 - "§b★★★"
 - "§d★★★★"
 - "§e★★★★★"
 - "§c★★★★★★"
强化增加属性: 1
# 完全随机哦..
# 除了击退值不加
# 这里是属性的百分比 也可以是纯数字
稀有度:
 - 名称: "§o§7D"
   随机范围: "1 - 2"
 - 名称: "§o§aC"
   随机范围: "4 - 8"
 - 名称: "§o§bB"
    随机范围: "20% - 50%"
 - 名称: "§o§dA"
    随机范围: "100% - 200%"
 - 名称: "§o§eS"
    随机范围: "150% - 300%"
强化等级限制: 12
洗练消耗: 10000
强化消耗金币: 5000
# 总开关
装备是否显示创造背包: true
