# 增加全部可增加数值(对宝石无效)
武器等级:
 - "§l§e✬§7✩✩✩✩✩"
 - "§l§e✬✬§7✩✩✩✩"
 - "§l§e✬✬✬§7✩✩✩"
 - "§l§e✬✬✬✬§7✩✩"
 - "§l§e✬✬✬✬✬§7✩"
 - "§l§e✬✬✬✬✬✬"
强化增加属性: 1
# 完全随机哦..
# 除了击退值不加
# 这里是属性的百分比 也可以是纯数字

稀有度:
  - 名称: "§o§7D"
    随机范围: "1 - 2"
  - 名称: "§o§aC"
    随机范围: "4 - 8"
  - 名称: "§o§bB"
    随机范围: "20% - 50%"
  - 名称: "§o§dA"
    随机范围: "100% - 200%"
  - 名称: "§o§eS"
    随机范围: "150% - 300%"
# 强化等级限制: 12 移动到装备配置文件
# 最低 1% 最高 100%
强化成功率算法: "100 - ({强化等级} * {稀有度})"
洗练消耗: 10000
洗练消耗金币算法: "({稀有度} + 1) * 10000"
强化消耗金币算法: "({稀有度} * 5000) * {强化等级}"
# 总开关
装备是否显示创造背包: true
是否显示底部: true

# 后期更新 暂不可用
强化石:
  - id: "388:0"
    name: "普通强化石"
    成功率加成: "50 - ({强化等级} * {稀有度})"
    强化装备:
      属性加成:
        伤害: 2


